sudo: false
language: perl
perl:
- '5.24'
before_install:
- git config --global user.name "TravisCI"
install:
- cpanm Carton
- carton install --deployment
script:
- carton exec -- prove --verbose
notifications:
  slack:
    secure: GecpDTau4nziTdV380rfQ82rJcWLLPiDPf6OahqLnh+meKQs7cgGZBpIc1LqIfFPOusxg7ofaZLx+u6Ijbn3h0DjZ+oYMjH1QHr5iMPLVvtNEZYpKxA4yO8TO2R3SrgEeXO3c5kxW1iDMnoDfzp08Ak4JC/HSqE0EirBlOSAFEA=
